
package com.example.mybatis.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PortalServicePortType", targetNamespace = "webservices.Portal.weaver.com.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PortalServicePortType {


    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getOneWorkflowInfo", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetOneWorkflowInfo")
    @ResponseWrapper(localName = "getOneWorkflowInfoResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetOneWorkflowInfoResponse")
    public String getOneWorkflowInfo(
        @WebParam(name = "in0", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in1);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getPortalDetailInfo", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetPortalDetailInfo")
    @ResponseWrapper(localName = "getPortalDetailInfoResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetPortalDetailInfoResponse")
    public String getPortalDetailInfo(
        @WebParam(name = "in0", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getAllWorkflow", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetAllWorkflow")
    @ResponseWrapper(localName = "getAllWorkflowResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetAllWorkflowResponse")
    public String getAllWorkflow();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getPortalMAinInfo", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetPortalMAinInfo")
    @ResponseWrapper(localName = "getPortalMAinInfoResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetPortalMAinInfoResponse")
    public String getPortalMAinInfo();

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getUserWorkflow", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetUserWorkflow")
    @ResponseWrapper(localName = "getUserWorkflowResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetUserWorkflowResponse")
    public String getUserWorkflow(
        @WebParam(name = "in0", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "getUserId", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetUserId")
    @ResponseWrapper(localName = "getUserIdResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.GetUserIdResponse")
    public String getUserId(
        @WebParam(name = "in0", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in0);

    /**
     * 
     * @param in0
     * @param in1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "webservices.Portal.weaver.com.cn")
    @RequestWrapper(localName = "changePassword", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "webservices.Portal.weaver.com.cn", className = "com.example.mybatis.webService.ChangePasswordResponse")
    public String changePassword(
        @WebParam(name = "in0", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in0,
        @WebParam(name = "in1", targetNamespace = "webservices.Portal.weaver.com.cn")
        String in1);

}
