
package myTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUT", targetNamespace = "http://www.shenhuagroup.com.cn/MHDBXXJCXT")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SI03FA3SJGJZLXT2JTMHDBDBSJOUT {


    /**
     * 
     * @param parameters
     * @return
     *     returns myTest.SyncTaskResponse
     */
    @WebMethod(operationName = "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUT", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "syncTaskResponse", targetNamespace = "http://ws.task.portal.core.platform.shinfotech.com/", partName = "parameters")
    public SyncTaskResponse si03FA3SJGJZLXT2JTMHDBDBSJOUT(
        @WebParam(name = "syncTask", targetNamespace = "http://ws.task.portal.core.platform.shinfotech.com/", partName = "parameters")
        SyncTask parameters);

}
