
package myTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTService", targetNamespace = "http://www.shenhuagroup.com.cn/MHDBXXJCXT", wsdlLocation = "file:/Users/admin/Downloads/SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUT.wsdl")
public class SI03FA3SJGJZLXT2JTMHDBDBSJOUTService
    extends Service
{

    private final static URL SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_EXCEPTION;
    private final static QName SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_QNAME = new QName("http://www.shenhuagroup.com.cn/MHDBXXJCXT", "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUT.wsdl");
            //url = SI03FA3SJGJZLXT2JTMHDBDBSJOUTService.class.getResource("SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUT.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_WSDL_LOCATION = url;
        SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_EXCEPTION = e;
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService() {
        super(__getWsdlLocation(), SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_QNAME);
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_QNAME, features);
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService(URL wsdlLocation) {
        super(wsdlLocation, SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_QNAME);
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_QNAME, features);
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SI03FA3SJGJZLXT2JTMHDBDBSJOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SI03FA3SJGJZLXT2JTMHDBDBSJOUT
     */
    @WebEndpoint(name = "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTPort")
    public SI03FA3SJGJZLXT2JTMHDBDBSJOUT getSI03FA3SJGJZLXT2JTMHDBDBSJOUTPort() {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/MHDBXXJCXT", "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTPort"), SI03FA3SJGJZLXT2JTMHDBDBSJOUT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SI03FA3SJGJZLXT2JTMHDBDBSJOUT
     */
    @WebEndpoint(name = "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTPort")
    public SI03FA3SJGJZLXT2JTMHDBDBSJOUT getSI03FA3SJGJZLXT2JTMHDBDBSJOUTPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.shenhuagroup.com.cn/MHDBXXJCXT", "SI_03FA3_SJGJZLXT2JTMHDB_DBSJ_OUTPort"), SI03FA3SJGJZLXT2JTMHDBDBSJOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_EXCEPTION!= null) {
            throw SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_EXCEPTION;
        }
        return SI03FA3SJGJZLXT2JTMHDBDBSJOUTSERVICE_WSDL_LOCATION;
    }

}
